version: 2.1

orbs:
  checkmrx-soap: nukengprod/checkmarx-soap@2.0.4
  aws-s3: circleci/aws-s3@2.0.0

executors: 
  base:
    environments: 
    ANT_OPTS: "-Xmx2g"
    docker:
      -image: circleci/openjdk:8-jdk

jobs:
  build_dev_artifacts:
    executor: base
    steps: 
    - checkout
    - build:
        build_file: build.xml
        env: DEV
    - persist_to_workspace: 
      root: /home/circleci/build-linux
      paths:
        - informatica-ec2-linux.tar

workflows:
  version: 2.1
  Informatica: 
    jobs: 
      - build_dev_artifacts:
          name: Build_dev_artifacts
      - version_and_tag:
          name: Create version and tag
          requires: 
            - build_dev_artifacts


