version: 2.1

orbs:
  checkmrx-soap: nukengprod/checkmarx-soap@2.0.4
  win: circleci/windows@2.2.0

executors: 
  base:
    win/default: 
      - powershell

jobs:
  build_dev_artifacts:
    executor: base
    steps: 
    - checkout
    - build:
        build_file: build.xml
        env: DEV
    - persist_to_workspace: 
      root: /home/circleci/build-linux
      paths:
        - informatica-ec2-linux.tar

workflows:
  version: 2.1
  Informatica: 
    jobs: 
      - build_dev_artifacts:
          name: Build_dev_artifacts
      - version_and_tag:
          name: Create version and tag
          requires: 
            - build_dev_artifacts


