version: 2.1

orbs:
  win: circleci/windows@2.4.1

jobs:
  build:
    executor:
      name: win/default
      size: medium
    steps:
      - checkout
      - run: 'Write-Host ''Hello, Windows'''

workflows:
  version: 2
  workflow:
    jobs:
    - build